src/lib.rs
Because json is unordered, the stored json params could sometimes be a different order than the one checked by the caller. Here, we convert to json and check equality of all fields. This came up in a fork on kinode; likely a different version of serde_json has different behavior wrt keeping/changing order of fields in a json object.
Note that I did not check for this same pattern elsewhere in the code. In general, we MUST NOT rely on the order of fields in a json object.
h/t @drunkplato
=> fix `get_capability()` params check

src/eth.rs, src/http.rs, src/vfs/mod.rs
Replace `uq`s in code with either `os` (for TLD) or `Ki` prefix.
=> replace `uq` with `Ki` prefix

src/http.rs
Note this is a breaking change to process_lib http ws functions.
=> http: remove unused `node` field from ws methods

Cargo.lock, Cargo.toml, src/http.rs, src/lib.rs
The goal here is to allow the server to serve multiple routes for the UI, so that the UI can use browser routing.
How this works:
1. The server responds to a specified route like `/users` with the UI
2. The UI routes the user to the correct page/view within the web app
=> Update and fix serve_ui and serve_index_html

src/http.rs
Slight change to the comment. Note that the current implementation means that this ext websocket can support both the ext AND FE with the same WS. Depending on decisions we make in the future wrt security, this may need to change; but this is the current behavior.
=> http: update `bind_ext_path()` comment

pull_request_template.md
We don't have a consistent PR format. In addition, we have to manually remind devs to update docs.
Add a template that provides a format & a reminder to update docs.
N/A
This is directed to `main` so it'll take effect immediately upon merge.
Note this is the same PR as https://github.com/kinode-dao/kinode/pull/251
=> add pull_request_template.md

pull_request_template.md, src/http.rs
Currently, it is possible to bind an HTTP path in `http_server` with a URL param like `/test/:test-id`, but it is not possible to get easy access to `:test-id` or the path that was originally bound.
This PR includes the updates to the IncomingHttpRequest, along with additional methods for parsing the `bound_path`
[Corresponding docs PR](https://github.com/kinode-dao/kinode-book/pull/135)
There will be a repo added that can be used to test http bindings and requests.
=> Updates to IncomingHttpRequest

Cargo.lock, Cargo.toml, src/eth.rs, src/kernel_types.rs
All ETH provider actions need a chain ID, so we can operate on all EVM chains
Add `chain_id: u64` to request types ([matching PR in kinode](https://github.com/kinode-dao/kinode/pull/266))
[Corresponding docs PR](https://github.com/kinode-dao/kinode-book/pull/143)
=> eth: add chain ID everywhere

src/eth.rs
Sync process_lib with PR in runtime: https://github.com/kinode-dao/kinode/pull/274
=> sync with runtime

src/http.rs
Syncing with runtime
Need an unbind action
[Corresponding docs PR](https://github.com/kinode-dao/kinode-book/pull/145)
=> HTTP server: add unbind action

src/lib.rs
=> docstring for await_next_request_body

Cargo.lock, Cargo.toml, src/lib.rs, src/net.rs
See runtime PR: https://github.com/kinode-dao/kinode/pull/295
=> add `net` section to lib, used for signing and verifying sigs

Cargo.lock, Cargo.toml
Alloy deps are out of date and have a bug that we're hitting
Bump to their 0.7.0 (conveniently matching our runtime version)
N/A
This is a breaking change since new alloy types don't mesh with old alloy types -- processes will have to upgrade to this version in their process deps if they want to use it.
=> 0.7.0: bump alloy deps

Cargo.lock, Cargo.toml, src/types/on_exit.rs
Ownership issues when using `on_exit::add_request()`. 
Use the mutable reference.
None
Add'l context: https://discord.com/channels/1186394868336038080/1250566699112206450
=> on_exit: use mut ref

Cargo.lock, Cargo.toml, src/types/capability.rs
We have methods on `Capability` here that don't match core. See e.g. https://github.com/kinode-dao/kinode/pull/434
Make them match.
None
Should be merged with core 0.8.3
=> match caps impls to core

src/eth.rs, src/kimap.rs, src/net.rs
Race condition with KNSUpdate of relevant name getting to net runtime before app_store already asks for it.
include a blocknumber option in the enum, kns_indexer checks if it's up to date with that.
=> GetName(hash, block) from KNS

src/vfs/directory.rs, src/vfs/file.rs
We have a create flag passed to our usual `open_dir` and `open_file` methods. This corresponds to the API in `std::fs` and `tokio::fs` like here: 
```rust
tokio::fs::OpenOptions::new()
.read(true)
.write(true)
.create(create)
```
Now, if you pass a create(true) to a file that already exists, it will fail with a FileAlreadyExists error. 
We could match on this specific error in core/vfs.rs, but I think rather than that, have a helper function here that makes 2 calls.
`vfs::open_or_create_file/dir` helpers that first try opening a file/dir with create: false, then create:true. 
[Corresponding docs PR](https://github.com/kinode-dao/kinode-book/pull/my-pr-number)
{Any other information useful for reviewers.}
=> vfs: open_or_create

src/lib.rs
When debugging processes, devs can often forget to import process libs `println!` macro without getting errors, as the rust compiler will just think it's the standard `println!` macro. 
Replacing `println!` with `kiprintln!` to prevent ambiguity.
TODO
More specific logging could also do the trick, open to suggestions!
=> Add `kiprintln!` on top of `println!`

src/vfs/file.rs
We run out of file descriptors. Work is ongoing to fix this at an OS level, but we should also clean up after ourselves: close files in VFS on drop.
On drop, `CloseFile`.
None
None
=> vfs: file drop file is close

src/kv.rs, src/sqlite.rs
when working with helper structs, it can be useful to clone and store them in state somewhere (as nested pointers to state and other things), but we cannot clone or serialize these right now.
Add traits!
None.
=> kv & sqlite: add Clone and Serialize traits 

Cargo.lock, src/http/server.rs
Some stuff in http doesn't work & other parts need workarounds. Partially addresses #110
1. `pub use` instead of `use` `StatusCode` which allows `send_response()` to work again.
2. First part of #110
None
None
=> http fixes

src/lib.rs
When we `Spawn()` (e.g. see [here](https://github.com/kinode-dao/kit/pull/275#issuecomment-2487143232)) the linter/analyzer gets mad because that function doesn't exist.
Add a noop macro, `Spawn!()`. We'll replace this instead of `Spawn()`, but then the linter will be happy and display whatever docs we write on it.
None yet.
Connected to https://github.com/kinode-dao/kit/pull/275
=> add `Spawn!()` noop macro

Cargo.lock, Cargo.toml, src/http/server.rs
Removing encrypted flag in core
Remove it here too
TODO
Bump version to 0.10
=> remove encrypted flag (version -> 0.10)

src/http/client.rs, src/http/server.rs, src/kimap.rs, src/lib.rs, src/net.rs
https://github.com/kinode-dao/kinode/issues/527
Switch `_`s to `-`s
TODO
Don't merge until https://github.com/kinode-dao/kinode/pull/589
=> change `_`s to `-`s

src/types/message.rs, src/types/request.rs, src/types/response.rs
https://github.com/kinode-dao/kinode/issues/581
Make use of the pattern from https://github.com/kinode-dao/kinode/pull/596 in a process_lib method.
None
None
=> request,response: add `attach_all()` method

src/http/server.rs
We added last-blob; should we use it anywhere?
Only obvious place it might be useful is in http-server.
None
None
=> http-server: use last_blob in request handler

src/sqlite.rs
https://github.com/kinode-dao/kinode/pull/642
=> sqlite: new types from runtime

Cargo.toml, src/eth.rs
Sister PR to https://github.com/kinode-dao/kinode/pull/681
TODO
None
=> add rpc url auth

Cargo.lock, Cargo.toml, src/hypermap.rs, src/lib.rs
First block was for old deployment
Update to new deployment, see https://basescan.org/tx/0xc2008d8e5bbd117410ca16c739acbd42e420ec9c52488e916af7a235dc6fb4c8
None
None
=> hypermap: update first block for new deployment

Cargo.lock, Cargo.toml, src/types/lazy_load_blob.rs, src/types/send_error.rs
App Framework needs to (de)serialize SendError, and hence, LazyLoadBlob.
Add base64-based (de)seralization to work nicely with JSON.
None
None
=> add (de)serialization methods for blob & SendError

src/logging.rs, src/vfs/file.rs
Remote logging serializes logs to Vec<u8> which is very efficient for JSON (it becomes an array of numbers).
Serialize logs to String instead for more efficient sending.
[TODO](https://github.com/hyperware-ai/hyperware-book/issues/280)
None
=> logging: change remote log serialization format to string for more efficient sending

hyperware-wit/hypermap-cacher:sys-v0.wit, hyperware-wit/process-lib.wit, hyperware-wit/sign:sys-v0.wit, src/eth.rs, src/hypermap.rs, src/lib.rs, src/sign.rs
https://github.com/hyperware-ai/hyperdrive/pull/736
=> add hypermap-cacher

src/hyperapp.rs
https://github.com/hyperware-ai/hyperprocess-macro/pull/39
=> hyperapp: add spawn
